name: DanielFrancavilla
favicon: null
layout_spectrum: 0.7266380931250751
typography_spectrum: 0.6706250144634396
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#060404'
    - '#c8bba9'
    - '#9f928b'
    - '#765d4a'
  brandStrength: 0.5
  lightness: 0.04603681550361216
  saturation: 0.3125
  rhythmicContrast: 0.005035860231146216
purpose: []
